"""add_error_message_to_task

Revision ID: c6ccac131b3d
Revises: 5a9a94795d00
Create Date: 2026-03-18 09:12:53.789452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ccac131b3d'
down_revision: Union[str, None] = '5a9a94795d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_tasks', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_tasks', 'error_message')
    # ### end Alembic commands ###
